global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'test-services'

scrape_configs:
  - job_name: 'test_service'
    metrics_path: '/products-api/v1/metrics'
    static_configs:
      - targets: ['products-service:10000']
        labels:
          service: 'products-service'
